### ISSUE TITLE
SEACR web server error

### ISSUE THREAD

**Issue by kpestal** [FredHutch/SEACR#21]
![image](https://user-images.githubusercontent.com/52841543/68151351-61ef6680-fef6-11e9-8468-933436b655d1.png)

getting this with everything I try to run, including stuff that has run fine previously.

**Comment by mpmeers** [comment]
This might be an issue with compatibility after adding a new version--tagging @dtenenba to see if he has ideas.

Mike

**Comment by dtenenba** [comment]
That was it. Fixed now.
