### ISSUE TITLE
*****WARNING: Query [...] is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.

### ISSUE THREAD

**Issue by leiendeckerlu** [FredHutch/SEACR#26]
Hi there,

after trimming, aligning sorting and dedpulicating my data in this way:

```
trim_galore --fastqc --gzip --phred33 --cores 4

bowtie2 -x --threads 24 --local --very-sensitive-local --no-unal --no-mixed --no-discordant --phred33 -I 10 -X 700 -1 ./${samplesCor}.bam.R1_val_1.fq.gz -2 ./${samplesCor}.bam.R2_val_2.fq.gz -S ${samplesCor}.sam

samtools view -h -S -b -o 

sambamba sort -t 12 -p -o

sambamba view -h -t 12 -p -f bam -F "[XS] == null and not unmapped and not duplicate"
```

I would like to create now the SEACR input files, however from the command 

`bedtools bamtobed -bedpe -i $sample.bam > $sample.bed`

I'm getting thousands of thousands of warnings like this:

> *****WARNING: Query D00689:433:CDT3LANXX:8:1110:18082:60094#AGCCTATC is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. 

Any idea what's going wrong here?

Many thanks,

Lukas

**Comment by mpmeers** [comment]
Hi Lukas,

It's likely that your BAM file is not sorted by name, which is a requirement for using bamtobed with the -bedpe flag (see documentation here: https://bedtools.readthedocs.io/en/latest/content/tools/bamtobed.html). You can sort by name using samtools sort -n before calling bamtobed. I will update the documentation in the next version to point this out. Let me know if this solves your issue.

Mike

**Comment by leiendeckerlu** [comment]
Hi Mike,

I missed that completely. Will try it out and report back.

Thanks,
Lukas

**Comment by leiendeckerlu** [comment]
Hi Mike,

I re-sorted the aligned BAMs by name but still get the same warning.

Any other idea?

If I look at the non-name sorted BAM in IGV it all looks good and valid.

Lukas

**Comment by leiendeckerlu** [comment]
Update:

It seems that it's a quite dramatic difference whether one uses:

```
sambamba view -h -t 12 -p -f bam -F "[XS] == null and not unmapped and not duplicate"

or

sambamba markdup -t 12

```

The first gives the mapping warning, the latter works.

Thanks for pointing out the sorting issue!

I'll close here.

Lukas
